name: Java Maven CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test -Pprod

      - name: Upload Test Results to GitHub
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports

      #   - name: Upload Extent Report
      #     if: always()
      #     uses: actions/upload-artifact@v4
      #     with:
      #       name: extent-report
      #       path: target/reports

      - name: Prepare Report for GitHub Pages
        run: |
          mkdir -p public
          report_file=$(find target/reports -name "*.html" | sort -V | tail -n 1)
          cp "$report_file" public/index.html

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
